server:
  port: 8862
#服务名称
spring:
  application:
    name: eureka-order
#服务地址
eureka:
  instance:
    hostname: 127.0.0.1
    #客户端每隔1秒向注册中心发送一次心条
    lease-renewal-interval-in-seconds: 1
    #eureka收到最后一次心跳等待的时间,单位为秒
    #超过时间注册中心将会剔除该服务
    lease-expiration-duration-in-seconds: 3
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8881/eureka/,http://127.0.0.1:8882/eureka/
    #注册该服务到eureka 单机状态不必要去注册
    register-with-eureka: true
    #是否需要去注册中心获取其它服务的地址信息
    fetch-registry: true
ribbon:
  # 请求连接的超时时间
  connectTimeout: 2000
  # 请求处理的超时时间
  readTimeout: 2000
  #对当前实例的重试次数
  maxAutoRetries: 2
  # 切换实例的重试次数  对失败的服务只访问3次
  maxAutoRetriesNextServer: 3
  #对所有操作请求都进行重试
  okToRetryOnAllOperations: true